### ISSUE TITLE
"failed to get account: failed to get item: failed to read password: The handle is invalid.

### ISSUE THREAD

**Issue by SpyGdev** [disfordottie/insaneAppPurchaser#2]
I have set up ipatool and insaneAppPurchaser, but I get this error when trying to use any exstisting list. Downloading single ipa with Ipatool works

**Comment by disfordottie** [comment]
Could you please provide a screenshot if possible? When exactly does it happen during the existing list?

Thanks for taking the time to report the error

**Comment by SpyGdev** [comment]
![Screenshot 2024-07-25 130551](https://github.com/user-attachments/assets/d170d230-e94b-4a9a-b6b2-522e953f094e)
here is the screenshot sir. It is failing to purchase them. Checking in my purchases on my iPhone, does not show them

**Comment by disfordottie** [comment]
That’s an ipatool error unfortunately, did it happen on one app or multiple? Try signing out and in of ipatool. And that error below it was my crap code and is fixed in the new update. It should be released in an hour or so.

You mentioned you can download IPAs with ipatool fine, can you purchase with it or does it give you that error?

**Comment by SpyGdev** [comment]
I can also purchase.I believe I understand the problem, ipatool uses phrapharase before purchasing, I think your script can ask for the pharaprase then start the purchasing procces then it might fix it, or is it possible to disable the phraprase on ipatool?

**Comment by SpyGdev** [comment]
another thing i found out is that on macos you can always allow, but on windows you cant.

**Comment by disfordottie** [comment]
What do you mean by paraphrase? The file related issue has been fixed in 1.2.1

Also what do you mean by you can always allow?

Thanks for taking the time to report all this aswell.

**Comment by SpyGdev** [comment]
Sorry for my shit English, On windows it requires a passphrase you set since their is no keychain. On macOS you can always allow keychain to be accessed.

**Comment by disfordottie** [comment]
Oh that makes more sense, when you got the error where you on a Mac or windows?

**Comment by SpyGdev** [comment]
I was on Windows, on my MacBook it's flawless.

**Comment by disfordottie** [comment]
👍 How did you get the bash script to run on windows

**Comment by SpyGdev** [comment]
It works up to the purchasing part. It tries to read locked email and password, so that's why it puts out the error

**Comment by disfordottie** [comment]
Does the file just open as normal?

**Comment by SpyGdev** [comment]
Yeah, it's a shell script file, it doesn't run natively but I use got bash
