### ISSUE TITLE
No lists found on the server

### ISSUE THREAD

**Issue by SplatzyXD** [disfordottie/insaneAppPurchaser#3]
self explanatory

**Comment by disfordottie** [comment]
Usually that means you have no internet or GitHub can’t be reached.

When exactly did it happen? Did you do other things first or did you got straight to lists?

**Comment by FaisalBiyari** [comment]
I have the same error, with internet working.
My work around was to download the list manually and rename it accordingly and go with option 1 for my own list.

**Comment by disfordottie** [comment]
Since the downloading lists part seems a bit hit or miss, i'll see if i can replace it with a better method. 

If anyone has any idea's please be my guest 😂

**Comment by FaisalBiyari** [comment]
Here's an idea:
Similar to the script accessing the bundleID.txt file
The script would have access to a List folder that has all the text files in it (similar to what you have in the repository files list)

The script would try to read the text file titles in the folder "Lists" and print them as options 1, 2, 3, etc.

<img width="765" alt="Screenshot 2024-07-26 at 8 33 14 AM" src="https://github.com/user-attachments/assets/ec67085f-4fdd-4d40-94f1-2237028622ea">

**Comment by disfordottie** [comment]
That's a good idea, and what I was originally going to do. But I wanted to store as little stuff on the host machine as possible.

I basically ended up doing exactly that but instead of storing them locally, they are stored in github and downloaded as needed, the only problem is it doesnt work for some people.

Thanks for taking the time to write your suggestion!

**Comment by jake01756** [comment]
Can confirm, I am also having this issue. I ended up downloading the "source" code and running it from there. It would be nice if scanned the list directory. The download option could then be kept (and improved).

**Comment by disfordottie** [comment]
I have found the fix, you need jq installed. I will add an automated installer but for now use brew install jq
