### ISSUE TITLE
Errors when try to run.

### ISSUE THREAD

**Issue by rkinlen** [disfordottie/insaneAppPurchaser#6]
`/workspaces/insaneAppPurchaser/Insane-iOS-App-Purchaser.sh: line 1386: unexpected EOF while looking for matching `"' `
`/workspaces/insaneAppPurchaser/Insane-iOS-App-Purchaser.sh: line 1404: syntax error: unexpected end of file`

**Comment by disfordottie** [comment]
Make sure you run it with either /path/to/file or cd /path/to then ./file

And not sh

Other than that re download the script

**Comment by RagingEnby** [comment]
@rkinlen were you ever able to get this sorted? Facing the same issue

**Comment by disfordottie** [comment]
How are you running the file?

**Comment by RagingEnby** [comment]
I'm using git bash
